target: model.segformer.SegFormer
params:
  num_classes: 3
  pretrained: model/weight/segformer_b2_backbone_weights.pth
  in_channels: 3
  embed_dims: [64, 128, 320, 512]
  num_heads: [1, 2, 5, 8]
  mlp_ratios: [4, 4, 4, 4]
  qkv_bias: True
  depths: [3, 4, 6, 3]
  sr_ratios: [8, 4, 2, 1]
  drop_rate: 0.0
  drop_path_rate: 0.1
  head_embed_dim: 768

