data:
  target: dataset.data_module.DataModule
  params:
    num_classes: 3
    # Path to training set configuration file.
    train_config: config/dataset/tunnel_defect_train.yaml
    # Path to validation set configuration file.
    val_config: config/dataset/tunnel_defect_val.yaml

model:
  target: model.model_module.ModelModule
  params:
    model_config: config/model/segformer.yaml
    resume:
    learning_rate: 1e-3

lightning:
  seed: 231
  
  trainer:
    accelerator: cuda
    precision: 32
    strategy: ddp
    # Indices of GPUs used for training.
    devices: 1
    num_nodes: 1
    # Path to save logs and checkpoints.
    default_root_dir: output
    # Max number of training steps (batches).
    max_steps: 25001
    # Validation frequency in terms of training steps.
    val_check_interval: 500
    check_val_every_n_epoch:
    log_every_n_steps: 50
    # Accumulate gradients from multiple batches so as to increase batch size.
    accumulate_grad_batches: 1
  
  logger:
    target: logger.wandb.WandbLogger
    params:
      project: generate_seg
  
  callbacks:
    - target: callback.image_logger.ImageLogger
      params:
        # Log frequency of image logger.
        log_every_n_steps: 1000
        max_images_each_step: 4
        log_images_kwargs: ~

    - target: callback.model_checkpoint.ModelCheckpoint
      params:
        # Frequency of saving checkpoints.
        every_n_train_steps: 5000
        save_top_k: -1
        filename: "{step}"
