dataset:
  target: dataset.crack500.Crack500Dataset
  params:
    file_list: /home/datasets/crack500/train.txt
    image_root: /home/datasets/crack500/images/validation
    annotation_root: /home/datasets/crack500/annotations/validation
    image_format: jpg
    annotation_format: png
    out_size: 128
    apply_transform: false

data_loader:
  batch_size: 32
  shuffle: false
  num_workers: 32
  drop_last: true
