dataset:
  target: dataset.cracktree200.CrackTree200Dataset
  params:
    train: false
    file_list: /home/datasets/cracktree200_gen/val.txt
    image_root: /home/datasets/cracktree200_gen/images/validation
    annotation_root: /home/datasets/cracktree200_gen/annotations/validation
    image_format: jpg
    annotation_format: png
    out_size: 512
    apply_transform: false

data_loader:
  batch_size: 16
  shuffle: false
  num_workers: 16
  drop_last: false
